//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Asignacion = new HashSet<Asignacion>();
            this.Contactos = new HashSet<Contactos>();
            this.Proyectos = new HashSet<Proyectos>();
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int Id_Cliente { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public string Nombre_Cliente { get; set; }
        public string Razon_Social_Cliente { get; set; }
        public string RFC_Cliente { get; set; }
        public string Calle_Cliente { get; set; }
        public string Exterior_Cliente { get; set; }
        public string Interior_Cliente { get; set; }
        public string Colonia_Cliente { get; set; }
        public string DelMun_Cliente { get; set; }
        public Nullable<short> CP_Cliente { get; set; }
        public string Estado_Dom_Cliente { get; set; }
        public string Dias_de_Pago_Cliente { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignacion> Asignacion { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contactos> Contactos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyectos> Proyectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
