//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public int Id_Contacto { get; set; }
        public int Id_Cliente { get; set; }
        public string Nombre_Contacto { get; set; }
        public string Puesto_Contacto { get; set; }
        public string Email_Contacto { get; set; }
        public string Telefono_Contacto { get; set; }
        public string Movil__Contacto { get; set; }
        public string Skype_Contacto { get; set; }
        public Nullable<bool> EnviaFactura_Contacto { get; set; }
        public string Comentario_Contacto { get; set; }
        public bool Estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
