//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public int Id_Contacto { get; set; }
        public int Id_Cliente { get; set; }
        public string Nombre_Contacto { get; set; }
        public string Puesto_Contacto { get; set; }
        public string Email_Contacto { get; set; }
        public string Telefono_Contacto { get; set; }
        public string Movil__Contacto { get; set; }
        public string Skype_Contacto { get; set; }
        public Nullable<bool> EnviaFactura_Contacto { get; set; }
        public string Comentario_Contacto { get; set; }
        public bool Estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
