//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosFacturas
    {
        public int IdDocumento { get; set; }
        public int IdFactura { get; set; }
        public string Url { get; set; }
        public string Descripción { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Facturas Facturas { get; set; }
    }
}
