//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoPermiso
    {
        public int Id_Empleado { get; set; }
        public int Id_Permiso { get; set; }
        public int Tipo_Permiso { get; set; }
    
        public virtual ctPermisos ctPermisos { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
