//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Asignacion = new HashSet<Asignacion>();
            this.EmpleadoPermiso = new HashSet<EmpleadoPermiso>();
            this.Empleados1 = new HashSet<Empleados>();
        }
    
        public int Id_Empleado { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public string Nombre_Empleado { get; set; }
        public string Email_Empleado { get; set; }
        public string Puesto_Empleado { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento_Empleado { get; set; }
        public Nullable<System.DateTime> Antiguedad_Empleado { get; set; }
        public string Skype_Empleado { get; set; }
        public string Domicilio_Empleado { get; set; }
        public string Telefono_L_Empleado { get; set; }
        public string Telefono_M_Empleado { get; set; }
        public Nullable<int> Id_JefeInmediato_Empleado { get; set; }
        public Nullable<int> IsLogIn { get; set; }
        public Nullable<int> Id_Perfil { get; set; }
        public string Usuario_Empleado { get; set; }
        public string Password_Empleado { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Salt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignacion> Asignacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadoPermiso> EmpleadoPermiso { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados1 { get; set; }
        public virtual Empleados Empleados2 { get; set; }
    }
}
