//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.DocumentosFacturas = new HashSet<DocumentosFacturas>();
        }
    
        public int IdFactura { get; set; }
        public int IdCliente { get; set; }
        public int IdEmpresa { get; set; }
        public Nullable<int> IdAsignacion { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public Nullable<int> C_Id_IVA { get; set; }
        public Nullable<int> C_Id_Moneda { get; set; }
        public Nullable<int> C_Id_Tipo_Cambio { get; set; }
        public Nullable<int> C_Id_Metodo_Pago { get; set; }
        public string Tipo_Factura { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio_Factura { get; set; }
        public Nullable<System.DateTime> Fecha_fin_Factura { get; set; }
        public Nullable<short> No_Factura { get; set; }
        public Nullable<decimal> Descuento_Factura { get; set; }
        public Nullable<decimal> Monto_Factura { get; set; }
        public Nullable<short> Ultimos_4_digitos_Factura { get; set; }
        public short Id_Estado_Factura { get; set; }
    
        public virtual Asignacion Asignacion { get; set; }
        public virtual C_Estado_Factura C_Estado_Factura { get; set; }
        public virtual C_IVA C_IVA { get; set; }
        public virtual C_Metodo_Pago C_Metodo_Pago { get; set; }
        public virtual C_Moneda C_Moneda { get; set; }
        public virtual C_Tipo_Cambio C_Tipo_Cambio { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Proyectos Proyectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosFacturas> DocumentosFacturas { get; set; }
    }
}
