//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectos
    {
        public int Id_Proyectos { get; set; }
        public Nullable<int> Id_Clientes_Proyectos { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public string Nombre_Proyectos { get; set; }
        public Nullable<System.DateTime> Fecha_Ini_Proyectos { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Proyectos { get; set; }
        public Nullable<decimal> Costo_Proyectos { get; set; }
        public Nullable<int> Id_Moneda_Proyectos { get; set; }
        public Nullable<int> Numero_Facturas_Proyectos { get; set; }
        public Nullable<int> Id_Tipo_Cambio_Proyectos { get; set; }
        public string Comentarios_Proyecto { get; set; }
        public Nullable<int> Id_IVA_Proyectos { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual C_IVA C_IVA { get; set; }
        public virtual C_Moneda C_Moneda { get; set; }
        public virtual C_Tipo_Cambio C_Tipo_Cambio { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
